### PR TITLE
OCPCLOUD-1427: Use BalancingIgnoredLabels in autoscaler test

### PR DESCRIPTION
**Pull request by RadekManak**
The autoscaler tests were removing UUID label from the machines to allow them to balance properly when scaling. I've changed that to use the new BalancingIgnoredLabels CRD option to tests it.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@RadekManak I suspect given the failures across all platforms that this isn't actually working as expected, can you investigate the test failures and see if you can see what went wrong? Is the autoscaler being configured correctly for example

**Comment by RadekManak** [comment]
I think this is broken as well. Will take a look when I have time.

**Comment by RadekManak** [comment]
There was a check in the test to make sure the labels are the same. I am now ignoring it in the comparison to test the Ignored labels feature.

**Comment by JoelSpeed** [comment]
Good catch, lets see if the tests pass 👀

**Comment by JoelSpeed** [comment]
/test e2e-aws-operator

/lgtm
/approve

GCP passed so I think this should be good

**Comment by RadekManak** [comment]
Let's give this PR another try, now that the test is improved.

**Comment by elmiko** [comment]
i wonder if we want to merge #272 before this?

**Comment by RadekManak** [comment]
I heard you talking about these changes and thought it was merged. Let's wait for that PR.
/hold

**Comment by elmiko** [comment]
ack, thanks Radek!

**Comment by JoelSpeed** [comment]
The dependent PR is now merged, but this now has merge conflicts which will need to be resolved

**Review by elmiko — COMMENTED** [review]
/lgtm

**Pull request merged**
