### PR TITLE
Bug 1732929: Pin to machine-api-operator to  release-4.1 branch

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
This PR is bumping vendored mao and pinning it to the release-4.1 branch. 
This is required to fix the failing ci job `ci/prow/e2e-aws-operator` at https://github.com/openshift/cluster-api-provider-aws/pull/253

### CODE REVIEW

**Comment by mfojtik** [comment]
@eparis another one i don't have label rights here

**Comment by ingvagabund** [comment]
`Tide query not found`, `This repo may not be configured to use Tide.`. This is also a repository containing only the machine test suite we run over every repo and which is not shipped to any customer at the moment.

**Comment by ingvagabund** [comment]
1. this repo contains only machine test suite
2. this is actually a bug fix that needs to be fixed asap so next time https://github.com/openshift/cluster-api-actuator-pkg is synced with changes in other repos we pull the right branch from mao
3. zero customer impact so all the code here is run only in the CI

**Pull request merged**
