### PR TITLE
Use v1beta1 and v1 versions of cluster-autoscaler-operator resources

### PR DESCRIPTION
**Pull request by bison**
Switches cluster-autoscaler-operator resources from v1alpha1 to v1beta1 and v1 versions.

### CODE REVIEW

**Comment by frobware** [comment]
All the builds appear as still running for k8s-e2e

/retest

**Comment by ingvagabund** [comment]
```
# kubectl logs -n kube-system cluster-autoscaler-operator-569d5545f9-swhcx
I0418 08:26:29.723126       1 main.go:13] Go Version: go1.10.3
I0418 08:26:29.723428       1 main.go:14] Go OS/Arch: linux/amd64
I0418 08:26:29.723437       1 main.go:15] Version: cluster-autoscaler-operator v0.0.0-128-g3ab7161-dirty
F0418 08:26:29.820657       1 main.go:30] no matches for kind "ClusterAutoscaler" in version "autoscaling.openshift.io/v1alpha1"
```

**Comment by ingvagabund** [comment]
```
# kubectl get clusterautoscaler -o yaml
apiVersion: v1
items:
- apiVersion: autoscaling.openshift.io/v1
  kind: ClusterAutoscaler
  metadata:
    creationTimestamp: 2019-04-18T08:30:11Z
    generation: 1
    labels:
      test.autoscaling.label: ""
    name: default
    namespace: ""
    resourceVersion: "1591"
    selfLink: /apis/autoscaling.openshift.io/v1/clusterautoscalers/default
    uid: 2e956f29-61b4-11e9-bbf1-0ab33762dd56
  spec:
    scaleDown:
      delayAfterAdd: 10s
      delayAfterDelete: 10s
      delayAfterFailure: 10s
      enabled: true
      unneededTime: 10s
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by ingvagabund** [comment]
CRD looks good:
```
# kubectl get crd clusterautoscalers.autoscaling.openshift.io -o yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"creationTimestamp":null,"name":"clusterautoscalers.autoscaling.openshift.io","namespace":""},"spec":{"group":"autoscaling.openshift.io","names":{"kind":"ClusterAutoscaler","listKind":"ClusterAutoscalerList","plural":"clusterautoscalers","singular":"clusterautoscaler"},"scope":"Cluster","subresources":{"status":{}},"validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"type":"string"},"kind":{"type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"maxPodGracePeriod":{"format":"int32","type":"integer"},"podPriorityThreshold":{"format":"int32","type":"integer"},"resourceLimits":{"properties":{"cores":{"properties":{"max":{"format":"int32","type":"integer"},"min":{"format":"int32","minimum":0,"type":"integer"}},"required":["min","max"],"type":"object"},"gpus":{"items":{"properties":{"max":{"format":"int32","minimum":1,"type":"integer"},"min":{"format":"int32","minimum":0,"type":"integer"},"type":{"minLength":1,"type":"string"}},"required":["type","min","max"],"type":"object"},"type":"array"},"maxNodesTotal":{"format":"int32","minimum":0,"type":"integer"},"memory":{"properties":{"max":{"format":"int32","type":"integer"},"min":{"format":"int32","minimum":0,"type":"integer"}},"required":["min","max"],"type":"object"}},"type":"object"},"scaleDown":{"properties":{"delayAfterAdd":{"pattern":"([0-9]*(\\.[0-9]*)?[a-z]+)+","type":"string"},"delayAfterDelete":{"pattern":"([0-9]*(\\.[0-9]*)?[a-z]+)+","type":"string"},"delayAfterFailure":{"pattern":"([0-9]*(\\.[0-9]*)?[a-z]+)+","type":"string"},"enabled":{"type":"boolean"},"unneededTime":{"pattern":"([0-9]*(\\.[0-9]*)?[a-z]+)+","type":"string"}},"required":["enabled"],"type":"object"}},"type":"object"},"status":{"type":"object"}}}},"version":"v1","versions":[{"name":"v1","served":true,"storage":true}]}}
  creationTimestamp: 2019-04-18T08:26:04Z
  generation: 1
  name: clusterautoscalers.autoscaling.openshift.io
  resourceVersion: "557"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/clusterautoscalers.autoscaling.openshift.io
  uid: 9b183ed3-61b3-11e9-bbf1-0ab33762dd56
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: autoscaling.openshift.io
  names:
    kind: ClusterAutoscaler
    listKind: ClusterAutoscalerList
    plural: clusterautoscalers
    singular: clusterautoscaler
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            maxPodGracePeriod:
              format: int32
              type: integer
            podPriorityThreshold:
              format: int32
              type: integer
            resourceLimits:
              properties:
                cores:
                  properties:
                    max:
                      format: int32
                      type: integer
                    min:
                      format: int32
                      minimum: 0
                      type: integer
                  required:
                  - min
                  - max
                  type: object
                gpus:
                  items:
                    properties:
                      max:
                        format: int32
                        minimum: 1
                        type: integer
                      min:
                        format: int32
                        minimum: 0
                        type: integer
                      type:
                        minLength: 1
                        type: string
                    required:
                    - type
                    - min
                    - max
                    type: object
                  type: array
                maxNodesTotal:
                  format: int32
                  minimum: 0
                  type: integer
                memory:
                  properties:
                    max:
                      format: int32
                      type: integer
                    min:
                      format: int32
                      minimum: 0
                      type: integer
                  required:
                  - min
                  - max
                  type: object
              type: object
            scaleDown:
              properties:
                delayAfterAdd:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
                delayAfterDelete:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
                delayAfterFailure:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
                enabled:
                  type: boolean
                unneededTime:
                  pattern: ([0-9]*(\.[0-9]*)?[a-z]+)+
                  type: string
              required:
              - enabled
              type: object
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ClusterAutoscaler
    listKind: ClusterAutoscalerList
    plural: clusterautoscalers
    singular: clusterautoscaler
  conditions:
  - lastTransitionTime: 2019-04-18T08:26:04Z
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
```

**Pull request merged**
