### PR TITLE
Remove import aliases to make tests more readable

### PR DESCRIPTION
**Pull request by alexander-demichev**
Remove import aliases to make tests more readable.

### CODE REVIEW

**Comment by enxebre** [comment]
wouldn't this more difficult with an IDE to check by autocompleting which functions provide each library?
Also if we do the change we'd want to do it everywhere consistently, not only in infra.

**Comment by alexander-demichev** [comment]
I don't think it can be a problem for IDE. Let me see where else these aliases can be removed.

**Comment by JoelSpeed** [comment]
/lgtm

They're `.` imported in most places I've ever seen it so no reason not to be the same

**Pull request merged**
