### PR TITLE
MIXEDARCH-258: Enable GCP in the arch aware scale from zero case

### PR DESCRIPTION
**Pull request by aleskandro**
Depends on openshift/machine-api-provider-gcp#60

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/approve
/lgtm

**Comment by aleskandro** [comment]
There is no pre-submit for GCP cases tagged as periodics. Could we unhold and track the next periodic run?

**Comment by aleskandro** [comment]
The test passed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-actuator-pkg/299/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e-gcp-periodic-pre/1716856325087956992

/unhold

**Pull request merged**
