### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by Fedosin**
Generated by:
`make fmt`

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by lobziik** [comment]
Just an fmt thingy, no need to retest

/skip

**Comment by lobziik** [comment]
/override ci/prow/e2e-vsphere-operator
/override ci/prow/e2e-azure-operator

There are only formatting changes and it does not touch test suite itself. No need to bother with retesting or insist for all jobs pass.

**Pull request merged**
