### PR TITLE
openstack: Increase timeouts

### PR DESCRIPTION
**Pull request by pierreprinetti**
Co-Authored-By: Martin André <maandre@redhat.com>

### CODE REVIEW

**Comment by pierreprinetti** [comment]
It looks like increased timeouts did good!

/cc @mandre

**Review by mandre — COMMENTED** [review]
> It looks like increased timeouts did good!

Indeed, the `Machine Suite: [Serial][Feature:Operators][Disruptive] When cluster-wide proxy is configured, Machine API cluster operator should create machines when configured behind a proxy` test succeeded this time, in 22m56s.

/lgtm

**Review by elmiko — COMMENTED** [review]
/approve

**Pull request merged**
