### PR TITLE
Remove machine finalizer under machine health check test

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Possible the situation that finalizer remove fails, in this case, I still
want to pass the test and just to remove finalizer under the `AfterEach`
section.

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@enxebre @ingvagabund Hm additional strange portion of logs
```
I0414 14:02:48.064880       1 machinehealthcheck_controller.go:247] No remediaton action was taken. Machine ci-op-276h1nb1-79b09-26vpg-worker-us-east-1a-hbgnt with node ip-10-0-129-91.ec2.internal is healthy
...
W0414 14:03:30.745720       1 machinehealthcheck_controller.go:226] Machine ci-op-276h1nb1-79b09-26vpg-worker-us-east-1a-hbgnt has unhealthy node ip-10-0-129-91.ec2.internal with the condition Ready and the timeout 300s for 745.711424ms. Requeuing...
...
W0414 14:03:30.751568       1 machinehealthcheck_controller.go:226] Machine ci-op-276h1nb1-79b09-26vpg-worker-us-east-1a-hbgnt has unhealthy node ip-10-0-129-91.ec2.internal with the condition Ready and the timeout 300s for 751.558587ms. Requeuing...
...
W0414 14:03:36.093085       1 machinehealthcheck_controller.go:226] Machine ci-op-276h1nb1-79b09-26vpg-worker-us-east-1a-hbgnt has unhealthy node ip-10-0-129-91.ec2.internal with the condition Ready and the timeout 300s for 6.09307686s. Requeuing...
...
I do not understand from where comming this re-queue, 5 minutes still not pass
W0414 14:06:26.962224       1 machinehealthcheck_controller.go:226] Machine ci-op-276h1nb1-79b09-26vpg-worker-us-east-1a-hbgnt has unhealthy node ip-10-0-129-91.ec2.internal with the condition Ready and the timeout 300s for 2m56.962215706s. Requeuing...
...
and here it waited for 5 minutes
I0414 14:11:26.963016       1 machinehealthcheck_controller.go:216] machine ci-op-276h1nb1-79b09-26vpg-worker-us-east-1a-hbgnt has been unhealthy for too long, deleting
...
```

**Comment by vikaschoudhary16** [comment]
I believe this PR is not required. 
https://github.com/openshift/cluster-api-actuator-pkg/pull/60#issuecomment-483220209

**Comment by cynepco3hahue** [comment]
@vikaschoudhary16 I still do not understand from what is coming additional reconciliation under https://github.com/openshift/cluster-api-actuator-pkg/pull/62#issuecomment-48312470. Do you have any ideas?

**Comment by ingvagabund** [comment]
No matter what is happening on the machine controller the side, removing the machine finalizer outside of the machine controller does not make sense.

**Comment by ingvagabund** [comment]
As pointed out in https://github.com/openshift/cluster-api-actuator-pkg/pull/62#issuecomment-483124704 the HC controller starts deleting the machine after ~8m30s after noticing the machine is unhealthy. I don't see any connection with the finalizer here.

**Pull request closed without merging**
