### PR TITLE
OCPCLOUD-1757: release-4.11, backport various improvements

### PR DESCRIPTION
**Pull request by damdo**
This PR backports various improvements to the package back into `release-4.11`.

### CODE REVIEW

**Comment by damdo** [comment]
e2e-azure-operator main test step passed here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-actuator-pkg/250/pull-ci-openshift-cluster-api-actuator-pkg-release-4.11-e2e-azure-operator/1587883270681399296#1:build-log.txt%3A42
But failed on deprovisioning. Retesting once more for luck.

**Comment by JoelSpeed** [comment]
> [6] [Fail] [Feature:MachineHealthCheck] MachineHealthCheck [AfterEach] should remediate unhealthy nodes 
[6] /go/src/github.com/openshift/cluster-api-actuator-pkg/pkg/framework/machinesets.go:424

MHC failure on Azure, plus, at the end a Machine was left over, I would have expected the cleanup logic to have sorted that 🤔 

/retest

**Comment by damdo** [comment]
We are talking about two different test runs here:

- In my comment I was talking about: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-actuator-pkg/250/pull-ci-openshift-cluster-api-actuator-pkg-release-4.11-e2e-azure-operator/1587883270681399296#1:build-log.txt%3A42

- Whilst in yours you are talking about https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-actuator-pkg/250/pull-ci-openshift-cluster-api-actuator-pkg-release-4.11-e2e-azure-operator/1587925721970380800#1:build-log.txt%3A7804-7805

**Review by JoelSpeed — COMMENTED** [review]
Reviewed each commit, changes look good
/lgtm
/approve

**Comment by JoelSpeed** [comment]
As this is a testing repo only, I'm going to override the bugzilla requirement and merge this

**Pull request merged**
