### PR TITLE
OCPCLOUD-2703: OWNERS: update subcomponent

### PR DESCRIPTION
**Pull request by nrb**
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
Is this supposed to be a Machine API Provider?
I think this repo will live longer than MAPI, and contains stuff for CPMS and may for CAPI in the future too.

**Comment by nrb** [comment]
The spreadsheet shows MAPI, but it does seem like it's not quite right. @JoelSpeed was this a mistake?

Screenshot 2024-09-05 at 12 31 33 PM

**Comment by JoelSpeed** [comment]
I had put it as MAPI because it's the MAPI E2E suite, but, if you'd rather put it as unknown I'm ok with that, I don't know which it fits better in

**Comment by damdo** [comment]
+1 for Unknown

**Review by damdo — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
