### PR TITLE
BUG 1835179: Add E2E validation for spot instances on AWS

### PR DESCRIPTION
**Pull request by JoelSpeed**
Adds a test to check that a MachineSet backed by spot instances on AWS will boot, join the cluster, and that Machines are annotated as interruptible as expected

### CODE REVIEW

**Comment by JoelSpeed** [comment]
This is currently failing because the Machine controller is unable to create spot instances
```
Error launching instance: AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.
```
Need to investigate

**Comment by enxebre** [comment]
awesome, thanks!
/approve

**Comment by enxebre** [comment]
bot will want a BZ

**Pull request merged**
