### PR TITLE
Bug 1948719: update k8s dependencies to 1.21

### PR DESCRIPTION
**Pull request by elmiko**
This change updates the go.mod and related vendor files to the
kubernetes 1.21 baseline. This was achieved by updating some of the
entries in go.mod and then running make vendor.

The updates to go.mod were as follows:
```
github.com/openshift/machine-api-operator master
```

Then ran `make vendor` to produce output.

### CODE REVIEW

**Comment by elmiko** [comment]
govet is failing here, but work locally. not quite sure why
/test govet

**Comment by JoelSpeed** [comment]
This is broken due to the Azure/AWS dependencies being out of date, these will need updating too

**Comment by elmiko** [comment]
i re-updated the vendor here, but i think that was premature. we need to wait for https://github.com/openshift/cluster-api-provider-azure/pull/214 and https://github.com/openshift/cluster-api-provider-gcp/pull/159 to merge, then re-vendor here. iiuc
/hold

**Comment by lobziik** [comment]
Also bunch of fixes needed due to runtime client changes :(

**Comment by elmiko** [comment]
thanks @lobziik! when the other PRs merge and i update this, i will add the changes from your patch.

**Comment by elmiko** [comment]
updated
* re-vendored with newly merged changes from dependencies
* added fixes for runtime.Object -> runtimeclient.Object
* removed unused function DeleteObjectsByLabels

**Comment by elmiko** [comment]
minor fixup for go vet errors, also reflowed the commits to make it easier to fix

**Comment by JoelSpeed** [comment]
/approve

Dependencies have been updated, no longer need the hold
/hold cancel

/retest

**Comment by elmiko** [comment]
still waiting on this for revendor, https://github.com/openshift/cluster-api-provider-gcp/pull/161

**Comment by JoelSpeed** [comment]
@elmiko The dependent PR has merged, could you try updating the MAO dependency here with the latest changes and see if it passes the tests? Feel free to hold cancel once you've pushed the changes

**Comment by elmiko** [comment]
thanks @JoelSpeed , i missed that other dep. i will update shortly.

**Comment by elmiko** [comment]
udpated
* revendored from other mao deps again

given that this change set now includes the updates that were added in #211, i am going to change that PR so we don't have duplicates.

**Pull request merged**
