### PR TITLE
e2e/openshift/suites: Remove duplicate test commentary

### PR DESCRIPTION
**Pull request by frobware**

### CODE REVIEW

**Comment by ingvagabund** [comment]
`pkg/e2e/openshift` gets removed once all repos are synced with ginkgo, so no need to fix this

**Comment by enxebre** [comment]
closing this since we'll remove `e2e/openshift` once all repos are synced with ginkgo
Please @ingvagabund  let's make sure the Readme is kept https://github.com/openshift/cluster-api-actuator-pkg/blob/master/pkg/e2e/openshift/README.md

**Pull request closed without merging**
