### PR TITLE
OCPCLOUD-2043: Update dependencies to K8s 1.27

### PR DESCRIPTION
**Pull request by damdo**
This updates the dependencies to the latest versions to support K8s 1.27.

TODO: update reference to machine-api-operator once https://github.com/openshift/machine-api-operator/pull/1142 merges

### CODE REVIEW

**Comment by damdo** [comment]
/hold
until https://github.com/openshift/machine-api-operator/pull/1142 merges

**Comment by JoelSpeed** [comment]
Have you considered using a global `ctx` variable within the tests instead of calling `context.Background()` the whole time, not ideal but a pattern we've used a lot in tests before

**Comment by damdo** [comment]
Yes I did consider it, although I wasn't sure how long it would take and whether it was worth it.
Anyway had a go at it now and was able to get it sorted in a reasonable amount of effort.

**Comment by JoelSpeed** [comment]
Changes look good, should probably squash the commits up though

**Comment by JoelSpeed** [comment]
/hold cancel

dependent PR merged and this was updated

**Pull request merged**
