### PR TITLE
Bug 2097607: Add Powervs support for Webhook tests

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Recently we have added webhooks for Power VS in mapio with the [PR](https://github.com/openshift/machine-api-operator/pull/998), So in this PR adding support for Power VS in Webhook tests

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Do we have powerVS CI that we can run on demand against this repository? At the moment we can't check that this test is passing easily

**Comment by JoelSpeed** [comment]
> I think currently we dont have PowerVS ci, Could you please help me with any existing CI reference so i can take a look

I can see some references to powerVS UPI workflows, do you know if the powerVS IPI workflows are configured yet? A quick search of the release repo suggest @deepsm007 might be working on that at the moment?

For this repo we need to add something like https://github.com/openshift/release/blob/519bb369335da754a7b08b06e130c0d90305603c/ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml#L44-L55

But for that we need a PowerVS IPI workflow that creates a cluster for us

**Comment by deepsm007** [comment]
> > I think currently we dont have PowerVS ci, Could you please help me with any existing CI reference so i can take a look
> 
> I can see some references to powerVS UPI workflows, do you know if the powerVS IPI workflows are configured yet? A quick search of the release repo suggest @deepsm007 might be working on that at the moment?
> 
> For this repo we need to add something like https://github.com/openshift/release/blob/519bb369335da754a7b08b06e130c0d90305603c/ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml#L44-L55
> 
> But for that we need a PowerVS IPI workflow that creates a cluster for us

You might be interested in https://steps.ci.openshift.org/workflow/openshift-e2e-powervs-ipi

**Comment by JoelSpeed** [comment]
I think this is what we want, it allows us to inject our own tests rather than using the default test suite, thanks @deepsm007 for the hints, https://github.com/openshift/release/blob/47ab5d921697af23b458620a674c79f68db57d87/ci-operator/step-registry/ipi/powervs/ipi-powervs-workflow.yaml

**Comment by Karthik-K-N** [comment]
Thanks @JoelSpeed and @deepsm007 for the inputs, Just confused on how to utilize this here to enable testing

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N I've created [openshift/release#29642](https://github.com/openshift/release/pull/29642), PTAL
Thank you, I will check

**Review by JoelSpeed — COMMENTED** [review]
We can't add CI right now but @Karthik-K-N has manually tested this and it works, so I'm happy to merge it
/approve
/lgtm

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-azure-operator

Azure CI is broken right now and this PR shouldn't affect the outcome anyway

**Pull request merged**
