### PR TITLE
OCPBUGS-14289: add a sleep to balance similar nodes test

### PR DESCRIPTION
**Pull request by elmiko**
this change adds a 60 second sleep to the balance similar nodes test so that the new nodes have proper time to acquire their capacity resources, and so that the autoscaler has time to update its records. through experimentation, it appears that 60 seconds is sufficient time for the autoscaler to become aware of the changes. ideally this will be remediated in the future, but for now this change is being proposed to help the stability of this test.

### CODE REVIEW

**Comment by elmiko** [comment]
hmm, i guess it's back to the drawing board on this one since AWS is failing now

**Comment by elmiko** [comment]
i _think_ this will make the test better, but i would still like to understand why things look so different during the early node creation for the autoscaler. it feels like the autoscaler is running with stale information. i wonder if decreasing the scan interval time (eg down from 15 seconds to 5 seconds) would make a difference.

**Comment by elmiko** [comment]
i've updated the wait time to 1 minute, and also added more information in the comments. i think we should merge this to help keep the testing queues happy, but i also would like to return to this issue once we have the 1.28 rebase from upstream as i have added more logging that will help in the future.

**Comment by elmiko** [comment]
@JoelSpeed ptal, i think this is as good as it will get for now

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm

We need to time box this investigation for now and we've seen good results adding a sleep. In the future it would be good to understand why the test fails when we don't have the sleep, but we need to move on for now.

**Pull request merged**
