### PR TITLE
Migrate API from MAO to openshift/api

### PR DESCRIPTION
**Pull request by JoelSpeed**
This bumps the openshift/api dependency and migrates all of the API imports from the MAO and actuator repos to the openshift/api repo, as it is their new home.

I also took the opportunity to align the import names to our convention, the package is now imported as `machinev1` across the repo.

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve

**Review by SamuelStuchly — APPROVED** [review]
Other than small nit looks good.
/lgtm

**Pull request merged**
